metadata:
  display-name: CloudNativePG Helm chart
  short-description: CloudNativePG is the Kubernetes operator that covers the full lifecycle of a highly available PostgreSQL database cluster with a primary/standby architecture, using native streaming replication.
  featured: false
  home-url: https://cloudnative-pg.io/
  categories:
    - databases-and-storage
