metadata:
  display-name: Docker
  short-description: The Docker CLI is the official command-line interface for Docker. It provides commands to build, run, and manage Docker containers and images.
  featured: false
  home-url: https://github.com/docker/cli
  categories:
    - developer-tools
  included-tools:
    - name: Docker CLI
      description: The Docker CLI is the official command-line interface for Docker
    - name: Docker Buildx
      description: Docker Buildx is a tool for building Docker images with BuildKit
    - name: Docker Compose
      description: Docker Compose is a tool for defining and running multi-container Docker applications
    - name: Docker Scout
      description: Docker Scout is a tool for scanning Docker images for security vulnerabilities
