# syntax=dhi.io/build:2-helm3

name: Grafana Alloy Helm chart 1.x
image: dhi.io/alloy-chart
variant: helm
tags:
  - 1.5.2
platforms:
  - linux/amd64
vars:
  ALLOY_IMAGE_TAG: 1.12.0
  ALLOY_REFERENCE: dhi/alloy:1.12.2-debian13@sha256:b6081e053d4ec1ef961c6d483a3a9325eb0558db0b216aeec4cd8f422b167376
  CHART_COMMIT_SHA: 7f1dbda4f084862e8252df6f784479ca6f22233f
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  PROMETHEUS_CONFIG_RELOADER_REFERENCE: dhi/prometheus-config-reloader:0.88.0-debian13@sha256:f12117f96beb2a97d1d0cf103e57194d6a82b8921134f6b0cddd14688f7248fd
  SEMVER_MAJOR_MINOR_VERSION: "1.5"
  SEMVER_MAJOR_VERSION: "1"
  SEMVER_VERSION: 1.5.2
  VERSION: 1.5.2
contents:
  builds:
    - name: alloy
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        packages:
          - bash
          - build-essential
          - coreutils
          - grep
          - libc-bin
          - sed
        files:
          - url: git+https://github.com/grafana/alloy.git#helm-chart/1.5.2
            checksum: 7f1dbda4f084862e8252df6f784479ca6f22233f
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            chart:
              appRef: alloy
              dependencies:
                - keep: true
                  name: crds
              description: Docker Hardened Images Helm chart for Grafana Alloy
              images:
                - name: alloy
                  ref: dhi/alloy:1.12.2-debian13@sha256:b6081e053d4ec1ef961c6d483a3a9325eb0558db0b216aeec4cd8f422b167376
                - name: prometheus-config-reloader
                  ref: dhi/prometheus-config-reloader:0.88.0-debian13@sha256:f12117f96beb2a97d1d0cf103e57194d6a82b8921134f6b0cddd14688f7248fd
              name: alloy-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/grafana/alloy
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts/alloy
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
            cmd: lint .
        - name: package
          uses: helm/package@v1
          work-dir: ${source.dir}/helm-charts/operations/helm/charts
          with:
            chart: alloy
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/alloy/config
