# syntax=dhi.io/build:2-helm3

name: Valkey Helm chart 0.x
image: dhi.io/valkey-chart
variant: helm
tags:
  - 0.9.3
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: 13b95820b80663d98ab1bb4a91ed8330a5405eef
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
  REDIS_EXPORTER_REFERENCE: dhi/redis-exporter:1.80.1-debian13@sha256:60dd0a8fd57131a8c2a0283cb0c8474e460f454939643025e703b1c6e451db51
  SEMVER_MAJOR_MINOR_VERSION: "0.9"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.9.3
  VALKEY_REFERENCE: dhi/valkey:9.0.1-debian13@sha256:f1c6f7af37287cb36e8e73e7a8c9b07f160296dde9a6429a4b1e7948ef9d4297
  VERSION: 0.9.3
contents:
  builds:
    - name: valkey
      uses: dhi.io/helm:3.19.5-debian13-dev@sha256:990351376bd8e5afc77dc61f88f8dd47e31ec480a59dd7b171370d89aadf0f74
      contents:
        files:
          - url: git+https://github.com/valkey-io/valkey-helm.git#valkey-0.9.3
            checksum: 13b95820b80663d98ab1bb4a91ed8330a5405eef
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/valkey
          with:
            chart:
              appRef: valkey
              description: Docker Hardened Images Helm chart for Valkey
              images:
                - name: valkey
                  ref: dhi/valkey:9.0.1-debian13@sha256:f1c6f7af37287cb36e8e73e7a8c9b07f160296dde9a6429a4b1e7948ef9d4297
                - name: redis-exporter
                  ref: dhi/redis-exporter:1.80.1-debian13@sha256:60dd0a8fd57131a8c2a0283cb0c8474e460f454939643025e703b1c6e451db51
              name: valkey-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/valkey-io/valkey-helm
            cmd: prepare
            registry: dhi.io
        - name: relocate chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/valkey
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update dependencies
          uses: helm/cmd@v1
          with:
            chart: ${source.dir}/helm-charts/valkey
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts
          with:
            chart: valkey
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/valkey
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/valkey/config
