# syntax=dhi.io/build:2-helm3

name: VictoriaMetrics Cluster Helm chart 0.x
image: dhi.io/victoriametrics-cluster-chart
variant: helm
tags:
  - 0.32.0
platforms:
  - linux/amd64
vars:
  CHART_COMMIT_SHA: fe149b12908348a67e251d544d619c6e6ead13a9
  DHI_NAMESPACE: dhi
  DHI_PREFIX: ""
  DHI_REGISTRY: dhi.io
  DHI_SKIP_CONTEXT_COPY: "true"
  HELM_REFERENCE: dhi/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
  SEMVER_MAJOR_MINOR_VERSION: "0.32"
  SEMVER_MAJOR_VERSION: "0"
  SEMVER_VERSION: 0.32.0
  VERSION: 0.32.0
  VMAUTH_REFERENCE: dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:01edd8633e3d83139f886e801794236e9445bf184f7fdda2e95d202293b15622
  VMINSERT_REFERENCE: dhi/victoriametrics-vminsert:1.133.0-debian13@sha256:6d34967bcdf5590c1d0834b985ee692dbd2272def92259e688ea7f77b2e663e3
  VMSELECT_REFERENCE: dhi/victoriametrics-vmselect:1.133.0-debian13@sha256:b2fe0a50a31fdfcde7437087ed6cd163212350a655044795f5aea259beac336b
  VMSTORAGE_REFERENCE: dhi/victoriametrics-vmstorage:1.133.0-debian13@sha256:96535714479cd48587c0e1250fd93a07cd8d16f38e5f12a6a37d22331b8bd9aa
contents:
  builds:
    - name: victoriametrics-cluster-chart
      uses: dhi.io/helm:3.19.4-debian13-dev@sha256:4a591aa3cad9e5a0b82d3503e6140956db99735b68351b7b223514220873df4c
      contents:
        files:
          - url: git+https://github.com/VictoriaMetrics/helm-charts.git#victoria-metrics-cluster-0.32.0
            path: ${source.dir}/helm-charts
            uid: 0
            gid: 0
      pipeline:
        - name: prepare chart
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            chart:
              appRef: victoriametrics-vmselect
              description: Docker Hardened Images Helm chart for VictoriaMetrics Cluster
              images:
                - name: victoriametrics-vmselect
                  ref: dhi/victoriametrics-vmselect:1.133.0-debian13@sha256:b2fe0a50a31fdfcde7437087ed6cd163212350a655044795f5aea259beac336b
                - name: victoriametrics-vmstorage
                  ref: dhi/victoriametrics-vmstorage:1.133.0-debian13@sha256:96535714479cd48587c0e1250fd93a07cd8d16f38e5f12a6a37d22331b8bd9aa
                - name: victoriametrics-vminsert
                  ref: dhi/victoriametrics-vminsert:1.133.0-debian13@sha256:6d34967bcdf5590c1d0834b985ee692dbd2272def92259e688ea7f77b2e663e3
                - name: victoriametrics-vmauth
                  ref: dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:01edd8633e3d83139f886e801794236e9445bf184f7fdda2e95d202293b15622
              name: victoriametrics-cluster-chart
              notes: ${source.dir}/config/NOTES.txt
              sourceUrl: https://github.com/VictoriaMetrics/helm-charts
            cmd: prepare
            registry: dhi.io
        - name: update chart values
          uses: helm/rudder@v1
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          with:
            cmd: patch
            patches:
              from: ${source.dir}/config
            registry: dhi.io
        - name: update sidecar values
          uses: yq/patch@v1
          with:
            file: ${source.dir}/helm-charts/charts/victoria-metrics-cluster/values-sidecar.yaml
            patches:
              - .extraContainers[0].image = "dhi/victoriametrics-vmauth:1.133.0-debian13@sha256:01edd8633e3d83139f886e801794236e9445bf184f7fdda2e95d202293b15622"
              - .extraContainers[0].securityContext.enabled = true
              - .extraContainers[0].securityContext.runAsNonRoot = true
              - .extraContainers[0].securityContext.runAsUser = 65532
              - .extraContainers[0].securityContext.runAsGroup = 65532
        - name: blank 3rd party images
          work-dir: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
          runs: |
            set -eux -o pipefail

            # Blank out the 3rd party images for victoriametrics/vmbackupmanager
            sed -i '/- name: vmbackupmanager/{n;s/^\([[:space:]]*image:\).*/\1 "" #THIS IMAGE IS NOT IN THE DHI CATALOG YET, PLEASE CONTACT THE DOCKER TEAM IF NEEDED/;}' ./templates/vmstorage-server.yaml
        - name: update dependencies
          uses: helm/cmd@v1
          privileged: true
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
            cmd: dependency update
        - name: lint
          uses: helm/cmd@v1
          work-dir: ${source.dir}/helm-charts/charts
          with:
            chart: victoria-metrics-cluster
            cmd: lint .
        - name: package
          uses: helm/package@v1
          with:
            chart: ${source.dir}/helm-charts/charts/victoria-metrics-cluster
      paths:
        - type: directory
          path: ${source.dir}/config
          uid: 0
          gid: 0
          mode: "0644"
          source: chart/victoriametrics-cluster/config
