image:
  repository: ${vector.registry}/${vector.repository}
  tag: ${vector.tag}
  sha: ${vector.digest}

haproxy:
  image:
    repository: ${haproxy.registry}/${haproxy.repository}
    tag: ${haproxy.tag}@${haproxy.digest}

podSecurityContext:
  enabled: true
  fsGroup: 65532
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
